# Generated by Django 4.2.16 on 2024-10-19 03:05

from django.db import migrations, models    

class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AaplStockData',
            fields=[
                ('timestamp', models.DateTimeField(primary_key=True, serialize=False)),
                ('open_price', models.DecimalField(decimal_places=4, max_digits=20)),
                ('close_price', models.DecimalField(decimal_places=4, max_digits=20)),
                ('high_price', models.DecimalField(decimal_places=4, max_digits=20)),
                ('low_price', models.DecimalField(decimal_places=4, max_digits=20)),
                ('volume', models.DecimalField(decimal_places=4, max_digits=20)),
            ],
            options={
                'db_table': 'aapl_stock_data',
            },
        ),
    ]
