# Generated by Django 4.2.16 on 2024-10-19 03:20

from django.db import migrations, models
from django.db import connection
import sys
from django.db import migrations

def create_hypertable(apps, schema_editor):
    from django.db import connection
    if 'test' not in sys.argv:
        with connection.cursor() as cursor:
            cursor.execute("SELECT create_hypertable('aapl_stock_data', 'time');")

class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='aaplstockdata',
            old_name='timestamp',
            new_name='time',
        ),
        migrations.RunPython(create_hypertable),
    ]
